{{- if .Values.autoscaling.worker.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ginsen-net8-async-milestone.fullname-worker" . }}
  labels:
    {{- include "ginsen-net8-async-milestone.labels-worker" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ginsen-net8-async-milestone.fullname-worker" . }}
  minReplicas: {{ .Values.autoscaling.worker.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.worker.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.worker.targetCPUUtilizationPercentage }}
    - type: ContainerResource
      containerResource:
        name: cpu
        container: {{ .Chart.Name }}-worker
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.worker.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.worker.targetMemoryUtilizationPercentage }}
    - type: ContainerResource
      containerResource:
        name: memory
        container: {{ .Chart.Name }}-worker
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.worker.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
