{{- if .Values.serviceAccount.api.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ginsen-net8-async-template.serviceAccountName-api" . }}
  labels:
    {{- include "ginsen-net8-async-template.labels-api" . | nindent 4 }}
  {{- with .Values.serviceAccount.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.api.automount }}
{{- end }}
