events { }
http {
    # Increase the "rate" value if browser developer tools or a network traffic tool 
    # indicates that requests are receiving a 503 - Service Unavailable status code.
    limit_req_zone $binary_remote_addr zone=one:10m rate=60r/s;
    server {
        listen 80;

        location / {
            root      /usr/share/nginx/html;
            try_files $uri $uri/ /index.html =404;
            add_header Blazor-Environment "Docker";

            # Increase the "burst" value if browser developer tools or a network traffic tool 
            # indicates that requests are receiving a 503 - Service Unavailable status code.
            limit_req zone=one burst=60 nodelay;
        }
    }
}