services:
  ginsen.net8.async.milestone.api:
    image: ${CONTAINER_REGISTRY-ghcr.io/gin-sen/}ginsen-net8-async-milestone-api:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: final-api
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION-Debug}
      # dockerfile: Ginsen.Net8.Async.Milestone.Api/Dockerfile
    networks:
      - backend-net


  ginsen.net8.async.milestone.worker:
    image: ${CONTAINER_REGISTRY-ghcr.io/gin-sen/}ginsen-net8-async-milestone-worker:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: final-worker
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION-Debug}
      # dockerfile: Ginsen.Net8.Async.Milestone.Worker/Dockerfile
    networks:
      - backend-net

      
  rabbit:
    image: rabbitmq:4-management
    networks:
      - backend-net


  postgres:
    image: postgres
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge