services:
  ginsen.net8.async.milestone.api:
    image: ${DOCKER_REGISTRY-}ginsen-net8-async-milestone-api
    build:
      context: .
      dockerfile: Dockerfile
      target: final-api
      # dockerfile: Ginsen.Net8.Async.Milestone.Api/Dockerfile
    networks:
      - backend-net


  ginsen.net8.async.milestone.worker:
    image: ${DOCKER_REGISTRY-}ginsen-net8-async-milestone-worker
    build:
      context: .
      dockerfile: Dockerfile
      target: final-worker
      # dockerfile: Ginsen.Net8.Async.Milestone.Worker/Dockerfile
    networks:
      - backend-net

      
  rabbit:
    image: rabbitmq:4-management
    networks:
      - backend-net


networks:
  backend-net:
    driver: bridge