//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ginsen.Net8.Async.Milestone.HttpClientGenerator.TypeScript {
    using System;
    using System.Collections.Generic;
    
    
    public partial class ApiClient : ApiClientBase {
        
        
        private List<RecordInfo> _DtosField;

        public List<RecordInfo> Dtos {
            get {
                return this._DtosField;
            }
        }

        private List<EndpointInfo> _EndpointsField;

        public List<EndpointInfo> Endpoints {
            get {
                return this._EndpointsField;
            }
        }

        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 7 "ApiClient.tt"
            this.Write("\n// DTO Interfaces\n");
            
            #line default
            #line hidden
            
            #line 9 "ApiClient.tt"

foreach (var dto in Dtos)
{

            
            #line default
            #line hidden
            
            #line 13 "ApiClient.tt"
            this.Write("export interface ");
            
            #line default
            #line hidden
            
            #line 13 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( dto.Name ));
            
            #line default
            #line hidden
            
            #line 13 "ApiClient.tt"
            this.Write(" {\n");
            
            #line default
            #line hidden
            
            #line 14 "ApiClient.tt"

    foreach (var prop in dto.Properties)
    {

            
            #line default
            #line hidden
            
            #line 18 "ApiClient.tt"
            this.Write("  ");
            
            #line default
            #line hidden
            
            #line 18 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 18 "ApiClient.tt"
            this.Write(": ");
            
            #line default
            #line hidden
            
            #line 18 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Type ));
            
            #line default
            #line hidden
            
            #line 18 "ApiClient.tt"
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 19 "ApiClient.tt"

    }

            
            #line default
            #line hidden
            
            #line 22 "ApiClient.tt"
            this.Write("}\n");
            
            #line default
            #line hidden
            
            #line 23 "ApiClient.tt"

}

            
            #line default
            #line hidden
            
            #line 26 "ApiClient.tt"
            this.Write("\n// ApiClient class\nexport class ApiClient {\n  constructor(private baseUrl: strin" +
                    "g) {}\n\n");
            
            #line default
            #line hidden
            
            #line 31 "ApiClient.tt"

foreach (var ep in Endpoints)
{
    var requestParam = !string.IsNullOrEmpty(ep.RequestType) ? $"request: {ep.RequestType}, " : "";

            
            #line default
            #line hidden
            
            #line 36 "ApiClient.tt"
            this.Write("  async ");
            
            #line default
            #line hidden
            
            #line 36 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.Name ));
            
            #line default
            #line hidden
            
            #line 36 "ApiClient.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 36 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( requestParam ));
            
            #line default
            #line hidden
            
            #line 36 "ApiClient.tt"
            this.Write("signal?: AbortSignal): Promise<");
            
            #line default
            #line hidden
            
            #line 36 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.ResponseType ?? "any" ));
            
            #line default
            #line hidden
            
            #line 36 "ApiClient.tt"
            this.Write(" | null> {\n    try {\n");
            
            #line default
            #line hidden
            
            #line 38 "ApiClient.tt"

    if (ep.HttpMethod == "GET")
    {

            
            #line default
            #line hidden
            
            #line 42 "ApiClient.tt"
            this.Write("      const res = await fetch(`${this.baseUrl}");
            
            #line default
            #line hidden
            
            #line 42 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.Route ));
            
            #line default
            #line hidden
            
            #line 42 "ApiClient.tt"
            this.Write("`, { method: \'GET\', signal });\n");
            
            #line default
            #line hidden
            
            #line 43 "ApiClient.tt"

    }
    else if (ep.HttpMethod == "POST")
    {

            
            #line default
            #line hidden
            
            #line 48 "ApiClient.tt"
            this.Write("      const res = await fetch(`${this.baseUrl}");
            
            #line default
            #line hidden
            
            #line 48 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.Route ));
            
            #line default
            #line hidden
            
            #line 48 "ApiClient.tt"
            this.Write("`, { method: \'POST\', headers: { \'Content-Type\': \'application/json\' }, body: JSON." +
                    "stringify(request), signal });\n");
            
            #line default
            #line hidden
            
            #line 49 "ApiClient.tt"

    }
    else
    {

            
            #line default
            #line hidden
            
            #line 54 "ApiClient.tt"
            this.Write("      // TODO: Implement ");
            
            #line default
            #line hidden
            
            #line 54 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.HttpMethod ));
            
            #line default
            #line hidden
            
            #line 54 "ApiClient.tt"
            this.Write(" method\n      const res = await fetch(`${this.baseUrl}");
            
            #line default
            #line hidden
            
            #line 55 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.Route ));
            
            #line default
            #line hidden
            
            #line 55 "ApiClient.tt"
            this.Write("`, { method: \'");
            
            #line default
            #line hidden
            
            #line 55 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.HttpMethod ));
            
            #line default
            #line hidden
            
            #line 55 "ApiClient.tt"
            this.Write("\', signal });\n");
            
            #line default
            #line hidden
            
            #line 56 "ApiClient.tt"

    }

            
            #line default
            #line hidden
            
            #line 59 "ApiClient.tt"
            this.Write("      if (!res.ok) return null;\n      return await res.json() as ");
            
            #line default
            #line hidden
            
            #line 60 "ApiClient.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ep.ResponseType ?? "any" ));
            
            #line default
            #line hidden
            
            #line 60 "ApiClient.tt"
            this.Write(";\n    } catch (e) {\n      // Optionally log error\n      return null;\n    }\n  }\n\n");
            
            #line default
            #line hidden
            
            #line 67 "ApiClient.tt"

}

            
            #line default
            #line hidden
            
            #line 70 "ApiClient.tt"
            this.Write("}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                if (((this.Session != null) 
                            && this.Session.ContainsKey("Dtos"))) {
                    object data = this.Session["Dtos"];
                    if (typeof(List<RecordInfo>).IsAssignableFrom(data.GetType())) {
                        this._DtosField = ((List<RecordInfo>)(data));
                    }
                    else {
                        this.Error("The type \'List<RecordInfo>\' of the parameter \'Dtos\' did not match the type passed" +
                                " to the template");
                    }
                }
                if (((this.Session != null) 
                            && this.Session.ContainsKey("Endpoints"))) {
                    object data = this.Session["Endpoints"];
                    if (typeof(List<EndpointInfo>).IsAssignableFrom(data.GetType())) {
                        this._EndpointsField = ((List<EndpointInfo>)(data));
                    }
                    else {
                        this.Error("The type \'List<EndpointInfo>\' of the parameter \'Endpoints\' did not match the type" +
                                " passed to the template");
                    }
                }
            }

        }
    }
    
    public class ApiClientBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
