<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.10.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Ginsen.Net8.Async.Milestone.Application/Ginsen.Net8.Async.Milestone.Application.csproj" />
    <ProjectReference Include="../Ginsen.Net8.Async.Milestone.Domain/Ginsen.Net8.Async.Milestone.Domain.csproj" />
  </ItemGroup>

</Project>
