{
 "title": "Worker",
 "description": "This dotnet-monitor dashboard is designed to show the default .NET metrics scraped using Managed Prometheus on Azure.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Service" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemruntime_working_set_bytes",
     "legendFormat": "Working Set"
    },
    {
     "expr": "systemruntime_gc_heap_size_bytes",
     "legendFormat": "GC Heap Size"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "systemruntime_cpu_usage_ratio", "legendFormat": "CPU Usage" }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_requests_per_second",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "systemruntime_exception_count", "legendFormat": "Exception Count" }
   ]
  },
  {
   "title": "Threadpool thread stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_thread_count",
     "legendFormat": "Threadpool thread count"
    },
    {
     "expr": "systemruntime_threadpool_queue_length",
     "legendFormat": "Threadpool queue length"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "GC Generation Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "systemruntime_gen_0_size_bytes", "legendFormat": "Gen 0 size" },
    { "expr": "systemruntime_gen_1_size_bytes", "legendFormat": "Gen 1 size" },
    { "expr": "systemruntime_gen_2_size_bytes", "legendFormat": "Gen 2 size" },
    { "expr": "systemruntime_poh_size_bytes", "legendFormat": "POH size" },
    { "expr": "systemruntime_loh_size_bytes", "legendFormat": "LOH size" }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "systemruntime_alloc_rate_bytes", "legendFormat": "Allocation rate bytes" }
   ]
  },
  {
   "title": "Time in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "systemruntime_time_in_gc_ratio", "legendFormat": "% Time in GC since last GC" }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "systemruntime_gc_fragmentation_ratio",
     "legendFormat": "GC Fragmentation"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "expr": "systemruntime_gen_0_gc_count", "legendFormat": "Gen 0 GC count" },
    { "expr": "systemruntime_gen_1_gc_count", "legendFormat": "Gen 1 GC count" },
    { "expr": "systemruntime_gen_2_gc_count", "legendFormat": "Gen 2 GC count" }
   ]
  }
 ]
}