{{- if and .Values.monitor.worker.istio.enabled .Values.monitor.worker.enabled }}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ include "ginsen-net8-async-milestone.fullname-worker" . }}-monitor
  labels:
    {{- include "ginsen-net8-async-milestone.labels-worker" . | nindent 4 }}
spec: 
  host: {{ printf "%s-monitor.%s.svc.cluster.local" (include "ginsen-net8-async-milestone.fullname-worker" .) .Release.Namespace }}
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user
          ttl: 900s
{{- end }}