{{- if and .Values.monitor.worker.enabled .Values.monitor.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ginsen-net8-async-milestone.fullname-worker" . }}-monitor
  labels:
    {{- include "ginsen-net8-async-milestone.labels-worker" . | nindent 4 }}
spec:
  type: {{ .Values.monitor.worker.service.type }}
  ports:
    - port: {{ .Values.monitor.worker.service.port }}
      targetPort: {{ .Values.monitor.worker.service.containerPort }}
      protocol: TCP
      name: monitor
  selector:
    {{- include "ginsen-net8-async-milestone.selectorLabels-worker" . | nindent 4 }}
{{- end }}