{
 "title": "dotnet-monitor dashboard",
 "description": "This dotnet-monitor dashboard is designed to show the default .NET metrics scraped using Managed Prometheus on Azure.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "service_name" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemruntime_working_set_bytes{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Working Set (api)"
    },
    {
     "expr": "systemruntime_gc_heap_size_bytes{job=\"dotnet-monitor-api\"}",
     "legendFormat": "GC Heap Size (api)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "systemruntime_cpu_usage_ratio{job=\"dotnet-monitor-api\"}",
     "legendFormat": "CPU Usage (api)"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_requests_per_second{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Requests per second (api)"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "systemruntime_exception_count{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Exception Count (api)"
    }
   ]
  },
  {
   "title": "Threadpool thread stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_thread_count{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Threadpool thread count (api)"
    },
    {
     "expr": "systemruntime_threadpool_queue_length{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Threadpool queue length (api)"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "GC Generation Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Gen 0 size (api)"
    },
    {
     "expr": "systemruntime_gen_1_size_bytes{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Gen 1 size (api)"
    },
    {
     "expr": "systemruntime_gen_2_size_bytes{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Gen 2 size (api)"
    },
    {
     "expr": "systemruntime_poh_size_bytes{job=\"dotnet-monitor-api\"}",
     "legendFormat": "POH size (api)"
    },
    {
     "expr": "systemruntime_loh_size_bytes{job=\"dotnet-monitor-api\"}",
     "legendFormat": "LOH size (api)"
    }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemruntime_alloc_rate_bytes{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Allocation rate bytes (api)"
    }
   ]
  },
  {
   "title": "Time in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_time_in_gc_ratio{job=\"dotnet-monitor-api\"}",
     "legendFormat": "% Time in GC since last GC (api)"
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "systemruntime_gc_fragmentation_ratio{job=\"dotnet-monitor-api\"}",
     "legendFormat": "GC Fragmentation (api)"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "systemruntime_gen_0_gc_count{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Gen 0 GC count (api)"
    },
    {
     "expr": "systemruntime_gen_1_gc_count{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Gen 1 GC count (api)"
    },
    {
     "expr": "systemruntime_gen_2_gc_count{job=\"dotnet-monitor-api\"}",
     "legendFormat": "Gen 2 GC count (api)"
    }
   ]
  }
 ]
}