name: helm validation

on:
  push:
    branches: [ main ]
    paths:
    - 'charts/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'charts/**'

env:
  DOTNET_VERSION: '8.0.X' # The .NET SDK version to use

jobs:
  validate:
    name: Validate Helm chart
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.6.3'
    - name: Validate Helm chart
      run: helm lint charts/ginsen-net8-async-milestone
    - name: Validate Helm chart
      run: >
        helm template 
          my-release charts/ginsen-net8-async-milestone 
          -n test --dry-run=client