name: Lint and Test Charts

on:
  pull_request:
    paths:
    - 'charts/**'
jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      REPOSITORY: ginsen-net8-async-milestone-charts
      USER: gin-sen
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Install Istio
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add istio https://istio-release.storage.googleapis.com/charts
          helm repo update
          helm install istio-base istio/base -n istio-system --set defaultRevision=default --create-namespace
          helm install istiod istio/istiod -n istio-system --wait
          kubectl create namespace test
          kubectl label namespace test istio-injection=enabled
          kubectl create secret docker-registry gh-regcred --namespace test --docker-server=https://${{ env.REGISTRY }} --docker-username=${{ env.USER }} --docker-password=${{ secrets.TOKEN }} --docker-email="${{ env.USER }}@users.noreply.github.com"

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --namespace test --helm-extra-set-args '--set=imagePullSecrets[0].name=gh-regcred' --helm-extra-args '--timeout 800s' --debug
