name: ci-milestone

on:
  push:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**/Dockerfile'
    - '**/appsettings*.json'
    paths-ignore:
    - '**/appsettings.Development.json'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '**/Dockerfile'
    - '**/appsettings*.json'
    paths-ignore:
    - '**/appsettings.Development.json'

env:
  DOTNET_VERSION: '8.0.X' # The .NET SDK version to use
    
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      DOCKER_IMAGE: gin-sen/ginsen-net8-async-milestone
      BUILD_CACHE: /home/runner/.docker/buildkit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Api
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{env.DOCKER_IMAGE}}-api:latest
          target: final-api
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.TOKEN }}

      - name: Build and push Worker
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{env.DOCKER_IMAGE}}-worker:latest
          target: final-worker
          cache-from: type=gha
          cache-to: type=gha,mode=max

  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore Ginsen.Net8.Async.Milestone.Template.csproj
      - name: Build
        run: dotnet pack --no-restore Ginsen.Net8.Async.Milestone.Template.csproj