name: ci-charts

on:
  push:
    branches: [ main ]
    paths:
    - 'charts/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'charts/**'

jobs:
  helm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      REGISTRY: ghcr.io
      REPOSITORY: ginsen-net8-async-milestone-charts
      USER: gin-sen
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Setup Helm
        uses: azure/setup-helm@v3
        
      - name: Helm login
        run: |
          echo "${{ secrets.TOKEN }}" | helm registry login ${{ env.REGISTRY }}/${{ env.USER }} -u ${{ env.USER }} --password-stdin
  
      - name: Helm lint & template
        run: |
          helm lint charts/ginsen-net8-async-milestone
          helm template ginsen-net8-async-milestone ./charts/ginsen-net8-async-milestone -n test --debug

      - name: Helm package
        run: helm package ./charts/ginsen-net8-async-milestone -d ./charts

      - name: Helm push
        run: helm push ./charts/*.tgz oci://${{ env.REGISTRY }}/${{ env.USER }}

      # chart.gz (404) Not Found
      - name: Helm Chart Releaser
        # You may pin to the exact commit or the version.
        # uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f
        uses: helm/chart-releaser-action@v1.7.0
        with:
          pages_branch: helm-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                