name: ci-milestone

on:
  push:

env:
  DOTNET_VERSION: '8.0.X' # The .NET SDK version to use
    
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ci/${{ github.job }}
      BUILD_CACHE: /home/runner/.docker/buildkit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Restore
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ginsen-net8-async-milestone:latest
          build-args: --target restore
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: Build and push Api
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ginsen-net8-async-milestone-api:latest
          build-args: --target final-api
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: Build and push Worker
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ginsen-net8-async-milestone-worker:latest
          build-args: --target final-worker
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache

  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
         dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore Ginsen.Net8.Async.Milestone.Template.csproj
      - name: Build
        run: dotnet pack --no-restore Ginsen.Net8.Async.Milestone.Template.csproj